### ISSUE TITLE
transparent buttons interact badly with dropdowns

### ISSUE THREAD

**Issue by mainej** [basscss/button-transparent#2]
Suppose you have a dropdown and a transparent button adjacent to it.  When the dropdown is open, if it covers the button the button captures clicks instead of the items in the dropdown, even though the dropdown is supposed to be "in front" of the rest of the content.

Part of the problem is that the transparent button has a z-index of 2.  An outline button has the same problem.

One solution is to set `z3` or `z4` on the `absolute` part of the dropdown, but I'd appreciate other suggestions.

**Comment by jxnblk** [comment]
`.z3` should work, but I think you might be encountering an issue with opacity and stacking contexts. I think you might want a new stacking context for the Dropdown menu. If you could share a codepen, that would be helpful.

**Comment by mainej** [comment]
Sorry, took me a few days to get back to this. Here's a [codepen](http://codepen.io/anon/pen/mJrGNj).

Adding `.z3` to the `.absolute` or removing `.button-transparent` both fix the stacking.

**Comment by jxnblk** [comment]
I think using `.z3` is the best solution for now. I'm in the process of updating button styles for `.button-transparent` and `.button-outline` that should help lower the z-index.

**Comment by mainej** [comment]
OK. Thanks for the update!

**Comment by mainej** [comment]
Just tried out https://github.com/basscss/btn. :+1:  I really like that the default is transparent, and that borders and backgrounds are layered on using other classes. It is a bit sad to lose that subtle feature of `.button-transparent` that on hover made the background a faint shade of the foreground color.  But, to me, I'd rather have the simplicty of `.btn` as an alternative.

In experimenting, I realized that `.btn` isn't `border-box`.  It's easy enough to create a class that adds that, but I thought I'd point it out in case you think it should be a feature of `.btn`.  If you'd prefer to move this conversation to that repo, let me know.

**Comment by jxnblk** [comment]
Yeah, the background shading thing is a bit tricky, so I think I'd like to keep the `.btn` alternative simpler. That said, it will probably have a custom property so that the default hover color can be adjusted independently of `--darken-1` – something like `--btn-hover-background-color`.

Border-box will probably be added to the `.btn` style, but feel free to open related issues on that repo.
